import Galaxy from './Assets/images/galaxy.webp';
import Ipad from './Assets/images/ipad.jpeg';
import Iphone from './Assets/images/iphone.png';
import Pixel from './Assets/images/pixel.jpg';

export const images = [Galaxy, Ipad, Iphone, Pixel];

export const products = [
  {
    id: 1,
    name: 'MacBook Air',
    brand: 'Apple',
    price: 999,
    instock: 10,
    description: 'A very good tablet',
    category: 'tablet',
    image: 'ipad.jpeg',
    count: 0,
    discount: 0,
    toDelete: false,
  },
  {
    id: 2,
    name: 'Galaxy',
    brand: 'Samsung',
    price: 599,
    instock: 10,
    description: 'A very good tablet',
    category: 'tablet',
    image: 'galaxy.webp',
    count: 0,
    discount: 0,
    toDelete: false,
  },
  {
    id: 3,
    name: 'Spacebook',
    brand: 'Lenovo',
    price: 700,
    instock: 10,
    description: 'A very good notebook',
    category: 'notebook',
    image: 'lenovo.jpg',
    count: 0,
    discount: 0,
    toDelete: false,
  },
  {
    id: 4,
    name: 'Surface',
    brand: 'Microsoft',
    price: 499,
    instock: 10,
    description: 'A very good notebook',
    category: 'notebook',
    image: 'surface.jpeg',
    count: 0,
    discount: 0,
    toDelete: false,
  },
  {
    id: 5,
    name: 'Pixel 7',
    brand: 'google',
    price: 499,
    instock: 10,
    description: 'A very good notebook',
    category: 'phone',
    image: 'pixel.jpg',
    count: 0,
    discount: 0,
    toDelete: false,
  },
  {
    id: 6,
    name: 'Iphone 10',
    brand: 'Apple',
    price: 499,
    instock: 5,
    description: 'A very good phone',
    category: 'phone',
    image: 'iphone.png',
    count: 0,
    discount: 0,
    toDelete: false,
  },
];
